# Site settings
title: PaoloBattistella.dev
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima settings
minima:
  date_format: "%-d %b %Y"

show_excerpts: true # set to true to show excerpts on the homepage
markdown: kramdown # markdown processor

# Minima: custom header links
header_pages:
  - _pages/about.md

include:
  - _pages

# generate social links in footer
github_username: paolobattistella
linkedin_username: paolobattistella
